/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type AccountType = "asset" | "liability" | "locked";

export type EmailVerificationCodePurpose = "change_email" | "password_reset" | "signup";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountBalances {
  account_id: string;
  balance: Generated<Numeric>;
  id: Generated<string>;
  updated_at: Generated<Timestamp | null>;
}

export interface Accounts {
  account_type: ArrayType<AccountType>;
  color: Generated<string>;
  icon: Generated<string>;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp | null>;
}

export interface EmailVerificationCodes {
  code: string;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  purpose: EmailVerificationCodePurpose;
  tmp_user_id: string | null;
  user_id: string | null;
}

export interface EnvelopAllocations {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string;
  envelop_id: string;
  id: Generated<string>;
}

export interface EnvelopBalances {
  allocated: Generated<Numeric>;
  consumed: Generated<Numeric>;
  envelop_id: string;
  remaining: Generated<Numeric>;
}

export interface Envelops {
  color: Generated<string>;
  created_at: Generated<Timestamp>;
  description: string | null;
  icon: Generated<string>;
  id: Generated<string>;
  name: string;
  space_id: string;
  updated_at: Generated<Timestamp | null>;
}

export interface Events {
  color: Generated<string>;
  created_at: Generated<Timestamp>;
  description: string | null;
  end_time: Timestamp;
  icon: Generated<string>;
  id: Generated<string>;
  name: string;
  space_id: string;
  start_time: Timestamp;
}

export interface ExpenseCategories {
  color: Generated<string>;
  created_at: Generated<Timestamp>;
  envelop_id: string;
  icon: Generated<string>;
  id: Generated<string>;
  name: string;
  parent_id: string | null;
  space_id: string;
  updated_at: Generated<Timestamp | null>;
}

export interface PlanAllocations {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  plan_id: string;
}

export interface PlanBalances {
  allocated: Generated<Numeric>;
  plan_id: string;
}

export interface Plans {
  color: Generated<string>;
  created_at: Generated<Timestamp>;
  description: string | null;
  icon: Generated<string>;
  id: Generated<string>;
  name: string;
  space_id: string;
  target_amount: Numeric | null;
  target_date: Timestamp | null;
  updated_at: Generated<Timestamp | null>;
}

export interface SpaceAccounts {
  account_id: string;
  created_at: Generated<Timestamp>;
  space_id: string;
}

export interface SpaceMembers {
  created_at: Generated<Timestamp>;
  role: ArrayType<"editor" | "owner" | "viewer">;
  space_id: string;
  user_id: string;
}

export interface Spaces {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp | null>;
  updated_by: string;
}

export interface TmpUsers {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  is_email_verified: Generated<boolean>;
}

export interface Transactions {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  created_by: string;
  description: string | null;
  destination_account_id: string | null;
  event_id: string | null;
  expense_category_id: string | null;
  id: Generated<string>;
  location: string | null;
  source_account_id: string | null;
  space_id: string;
  transaction_datetime: Generated<Timestamp>;
  type: ArrayType<"adjustment" | "expense" | "income" | "transfer">;
}

export interface UserAccounts {
  account_id: string;
  created_at: Generated<Timestamp>;
  role: ArrayType<"owner" | "viewer">;
  user_id: string;
}

export interface Users {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  first_name: string;
  id: Generated<string>;
  last_name: string;
  password_hash: string;
}

export interface DB {
  account_balances: AccountBalances;
  accounts: Accounts;
  email_verification_codes: EmailVerificationCodes;
  envelop_allocations: EnvelopAllocations;
  envelop_balances: EnvelopBalances;
  envelops: Envelops;
  events: Events;
  expense_categories: ExpenseCategories;
  plan_allocations: PlanAllocations;
  plan_balances: PlanBalances;
  plans: Plans;
  space_accounts: SpaceAccounts;
  space_members: SpaceMembers;
  spaces: Spaces;
  tmp_users: TmpUsers;
  transactions: Transactions;
  user_accounts: UserAccounts;
  users: Users;
}
