export const ROUTES = {
    root: "/",
    docs: "/docs",
    login: "/login",
    signup: "/signup",
    forgotPassword: "/forgot-password",
    spaces: "/spaces",
    profile: "/settings/profile",
    security: "/settings/security",
    myAccounts: "/accounts",
    space: (id: string) => `/s/${id}`,
    spaceOverview: (id: string) => `/s/${id}`,
    spaceAccounts: (id: string) => `/s/${id}/accounts`,
    spaceAccountDetail: (id: string, accId: string) => `/s/${id}/accounts/${accId}`,
    spaceTransactions: (id: string) => `/s/${id}/transactions`,
    spaceBudgets: (id: string) => `/s/${id}/budgets`,
    spaceBudgetDetail: (id: string, envId: string) => `/s/${id}/budgets/${envId}`,
    spaceBudgetMonth: (id: string, month: string) => `/s/${id}/budgets/month/${month}`,
    spaceReckoning: (id: string) => `/s/${id}/reckoning`,
    spaceYearReport: (id: string, year: number) => `/s/${id}/year/${year}`,
    spaceCategories: (id: string) => `/s/${id}/categories`,
    spaceEvents: (id: string) => `/s/${id}/events`,
    spaceEventDetail: (id: string, eventId: string) => `/s/${id}/events/${eventId}`,
    spaceAnalytics: (id: string) => `/s/${id}/analytics`,
    spaceAnalyticsDetail: (id: string, view: string) => `/s/${id}/analytics/${view}`,
    spaceSettings: (id: string) => `/s/${id}/settings`,
    inviteAccept: (token: string) => `/invite/${token}`,
} as const;
