export const ROUTES = {
    root: "/",
    login: "/login",
    signup: "/signup",
    forgotPassword: "/forgot-password",
    spaces: "/spaces",
    profile: "/settings/profile",
    security: "/settings/security",
    myAccounts: "/accounts",
    space: (id: string) => `/s/${id}`,
    spaceOverview: (id: string) => `/s/${id}`,
    spaceAccounts: (id: string) => `/s/${id}/accounts`,
    spaceAccountDetail: (id: string, accId: string) => `/s/${id}/accounts/${accId}`,
    spaceTransactions: (id: string) => `/s/${id}/transactions`,
    spaceEnvelopes: (id: string) => `/s/${id}/envelopes`,
    spaceEnvelopeDetail: (id: string, envId: string) => `/s/${id}/envelopes/${envId}`,
    spacePlans: (id: string) => `/s/${id}/plans`,
    spacePlanDetail: (id: string, planId: string) => `/s/${id}/plans/${planId}`,
    spaceCategories: (id: string) => `/s/${id}/categories`,
    spaceEvents: (id: string) => `/s/${id}/events`,
    spaceAnalytics: (id: string) => `/s/${id}/analytics`,
    spaceAnalyticsDetail: (id: string, view: string) => `/s/${id}/analytics/${view}`,
    spaceSettings: (id: string) => `/s/${id}/settings`,
} as const;
