export const ROUTES = {
    root: "/",
    docs: "/docs",
    login: "/login",
    signup: "/signup",
    forgotPassword: "/forgot-password",
    spaces: "/spaces",
    profile: "/settings/profile",
    security: "/settings/security",
    myAccounts: "/accounts",
    space: (id: string) => `/s/${id}`,
    spaceOverview: (id: string) => `/s/${id}`,
    spaceAccounts: (id: string) => `/s/${id}/accounts`,
    spaceAccountDetail: (id: string, accId: string) => `/s/${id}/accounts/${accId}`,
    spaceTransactions: (id: string) => `/s/${id}/transactions`,
    spaceEnvelopes: (id: string) => `/s/${id}/envelopes`,
    spaceEnvelopeDetail: (id: string, envId: string) => `/s/${id}/envelopes/${envId}`,
    spacePlanMonth: (id: string, month: string) => `/s/${id}/plan/${month}`,
    spaceReckoning: (id: string) => `/s/${id}/reckoning`,
    spaceYearReport: (id: string, year: number) => `/s/${id}/year/${year}`,
    spacePlans: (id: string) => `/s/${id}/plans`,
    spacePlanDetail: (id: string, planId: string) => `/s/${id}/plans/${planId}`,
    spaceCategories: (id: string) => `/s/${id}/categories`,
    spaceEvents: (id: string) => `/s/${id}/events`,
    spaceEventDetail: (id: string, eventId: string) => `/s/${id}/events/${eventId}`,
    spaceAnalytics: (id: string) => `/s/${id}/analytics`,
    spaceAnalyticsDetail: (id: string, view: string) => `/s/${id}/analytics/${view}`,
    spaceSettings: (id: string) => `/s/${id}/settings`,
    inviteAccept: (token: string) => `/invite/${token}`,
} as const;
