/**
 * Emoji half of the entity-icon system. A persisted icon is either a curated
 * Lucide key (see `entityIcons.ts`) or a raw emoji string; this module owns
 * validation, skin tones, the dataset shape (generated by
 * `pnpm generate-icons`, loaded lazily by `icons/load.ts`) and a
 * platform-support probe so the picker never offers emoji that the current
 * device would render as tofu.
 *
 * Keep module scope free of DOM access — `scripts/generate-icon-data.mts`
 * imports this file under Node.
 */

export type SkinTone = 0 | 1 | 2 | 3 | 4 | 5;

/** Fitzpatrick modifiers U+1F3FB…U+1F3FF, indexed by `SkinTone` (0 = none). */
export const SKIN_TONE_MODIFIERS: readonly string[] = [
    "",
    "\u{1F3FB}",
    "\u{1F3FC}",
    "\u{1F3FD}",
    "\u{1F3FE}",
    "\u{1F3FF}",
];
export const SKIN_TONE_LABELS: readonly string[] = [
    "Default",
    "Light",
    "Medium-light",
    "Medium",
    "Medium-dark",
    "Dark",
];
/** Swatches for the tone selector — default is the classic emoji yellow. */
export const SKIN_TONE_SWATCHES: readonly string[] = [
    "#ffcc4d",
    "#f7dece",
    "#f3d2a2",
    "#d5ab88",
    "#af7e57",
    "#7c533e",
];

/** System colour-emoji fonts, in the order platforms ship them. */
export const EMOJI_FONT_STACK =
    '"Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji", "Twemoji Mozilla", "EmojiOne Color", "Android Emoji", sans-serif';

const VARIATION_SELECTOR = "️";
const SKIN_TONE_RE = /[\u{1F3FB}-\u{1F3FF}]/u;
/** Country flags (regional-indicator pairs) and subdivision flags (tag sequences) — one platform feature. */
const FLAG_SEQUENCE_RE = /\p{Regional_Indicator}|[\u{E0020}-\u{E007F}]/u;

/**
 * Whole-string test for one RGI-shaped emoji sequence: a flag pair, a keycap,
 * or a pictograph with optional presentation selector / skin tone / tag
 * sequence, followed by any number of ZWJ-joined parts. Deliberately loose
 * (Extended_Pictographic covers reserved code points) so emoji newer than
 * this build still round-trip; anything that is not emoji-shaped — a stray
 * Lucide key, a word — is rejected and falls back to the default icon.
 */
const EMOJI_RE =
    /^(?:\p{Regional_Indicator}{2}|[#*0-9]️?⃣|\p{Extended_Pictographic}(?:️|\p{Emoji_Modifier})*(?:[\u{E0020}-\u{E007E}]+\u{E007F})?)(?:‍(?:\p{Extended_Pictographic}|\p{Emoji})(?:️|\p{Emoji_Modifier})*)*$/u;

export function isEmojiIcon(value: string | null | undefined): value is string {
    return !!value && EMOJI_RE.test(value);
}

/**
 * Identity of an emoji ignoring skin tone and presentation selectors, so a
 * stored "👍🏽" still highlights the "👍" cell in the picker.
 */
export function emojiKey(value: string): string {
    let key = "";
    for (const cp of value) {
        if (cp !== VARIATION_SELECTOR && !SKIN_TONE_RE.test(cp)) key += cp;
    }
    return key;
}

export function getSkinTone(value: string): SkinTone {
    for (const cp of value) {
        const i = SKIN_TONE_MODIFIERS.indexOf(cp);
        if (i > 0) return i as SkinTone;
    }
    return 0;
}

/**
 * Apply a skin tone to a *base* emoji (one the dataset flags as `skin`). The
 * modifier goes right after the first code point and replaces a presentation
 * selector there, which is how every single-person RGI sequence is built
 * (`☝️` → `☝🏽`, `🙋‍♀️` → `🙋🏽‍♀️`). Tone 0 returns the base untouched — the
 * base carries the canonical selector, which a stripped variant would lack.
 */
export function applySkinTone(base: string, tone: SkinTone): string {
    if (tone === 0) return base;
    const cps = Array.from(base).filter((cp) => !SKIN_TONE_RE.test(cp));
    const [first, ...rest] = cps;
    if (!first) return base;
    if (rest[0] === VARIATION_SELECTOR) rest.shift();
    return first + SKIN_TONE_MODIFIERS[tone] + rest.join("");
}

// ---------------------------------------------------------------------------
// Dataset
// ---------------------------------------------------------------------------

export interface EmojiEntry {
    /** Canonical RGI sequence, presentation selector included where required. */
    emoji: string;
    /** CLDR English name, e.g. "grinning face". */
    label: string;
    /** Index into `EmojiDataset.groups`. */
    group: number;
    /** Emoji spec version (0.6 … 17). */
    version: number;
    /** Space-separated extra search tokens (CLDR keywords + GitHub shortcodes). */
    tags: string;
    /** `applySkinTone()` produces a valid RGI sequence for this emoji. */
    skin: boolean;
    /** `emojiKey(emoji)`, precomputed. */
    key: string;
}

export interface EmojiDataset {
    groups: readonly string[];
    /** CLDR order, all groups concatenated. */
    entries: readonly EmojiEntry[];
    byKey: ReadonlyMap<string, EmojiEntry>;
    /** `[version, emoji]` newest first — one representative per spec version ≥ 11. */
    probes: ReadonlyArray<readonly [number, string]>;
    /** A country flag; regional-indicator flags are an all-or-nothing platform feature. */
    flagProbe: string;
}

type EmojiTuple = [
    emoji: string,
    label: string,
    group: number,
    version: number,
    tags: string,
    skin: 0 | 1,
];

/** Shape of `icons/emoji.generated.json`. */
export interface EmojiDataJson {
    groups: string[];
    flagProbe: string;
    probes: [number, string][];
    emojis: EmojiTuple[];
}

/**
 * Validate and expand the generated JSON. The checks are deliberately
 * shallow — a generator/runtime shape drift should fail loudly here rather
 * than as `undefined` labels in the grid.
 */
export function parseEmojiDataset(json: unknown): EmojiDataset {
    const data = json as Partial<EmojiDataJson> | null;
    if (
        !data ||
        !Array.isArray(data.groups) ||
        !Array.isArray(data.emojis) ||
        !Array.isArray(data.probes) ||
        !data.probes.every(
            (p) => Array.isArray(p) && typeof p[0] === "number" && typeof p[1] === "string"
        ) ||
        typeof data.flagProbe !== "string"
    ) {
        throw new Error("emoji.generated.json has an unexpected shape");
    }
    const entries: EmojiEntry[] = data.emojis.map((tuple) => {
        const [emoji, label, group, version, tags, skin] = tuple;
        if (
            typeof emoji !== "string" ||
            typeof label !== "string" ||
            typeof group !== "number" ||
            typeof version !== "number" || // a bad version would silently hide every emoji
            typeof tags !== "string" ||
            (skin !== 0 && skin !== 1)
        ) {
            throw new Error("emoji.generated.json has a malformed entry");
        }
        return { emoji, label, group, version, tags, skin: skin === 1, key: emojiKey(emoji) };
    });
    return {
        groups: data.groups,
        entries,
        byKey: new Map(entries.map((e) => [e.key, e])),
        probes: data.probes,
        flagProbe: data.flagProbe,
    };
}

// ---------------------------------------------------------------------------
// Platform support
// ---------------------------------------------------------------------------

export interface EmojiSupport {
    /** Highest Emoji spec version the device renders. */
    maxVersion: number;
    /** Country flags render — false on Windows. */
    flags: boolean;
}

/** Used when the canvas can't be trusted — Emoji 15.1 is universal on 2024+ OSes. */
const FALLBACK_SUPPORT: EmojiSupport = { maxVersion: 15.1, flags: true };
/**
 * Pixels below this alpha are anti-fingerprinting noise, not ink. Kept above
 * CHANNEL_TOLERANCE on purpose: a wide monochrome fallback bleeds into the
 * blue half, and with red already behind it the channel delta at an
 * anti-aliased edge equals the alpha byte.
 */
const VISIBLE_ALPHA = 64;
/** Red vs blue differ by 255 per channel; this band survives canvas-readback noise (Brave, Firefox RFP). */
const CHANNEL_TOLERANCE = 60;

let cachedSupport: EmojiSupport | null = null;

/**
 * Detect what this device can render by drawing probe emoji to a canvas:
 * a real colour glyph ignores `fillStyle` (so red and blue passes match),
 * while tofu and monochrome fallbacks take the fill colour, and an unsupported
 * ZWJ sequence splits into several glyphs and measures wider. Cached for the
 * session; ~10 draws in total. If even 😀 fails we can't tell "no colour-emoji
 * font" from a blocked or noised canvas (privacy browsers), so we assume a
 * modern platform rather than hide every emoji.
 */
export function detectEmojiSupport(dataset: EmojiDataset): EmojiSupport {
    if (cachedSupport) return cachedSupport;
    const probe = createCanvasProbe();
    if (!probe || !probe("\u{1F600}")) return (cachedSupport = FALLBACK_SUPPORT);
    let maxVersion = 10; // everything before Emoji 11 (2018) is assumed present
    for (const [version, emoji] of dataset.probes) {
        if (probe(emoji)) {
            maxVersion = version;
            break;
        }
    }
    return (cachedSupport = { maxVersion, flags: probe(dataset.flagProbe) });
}

function createCanvasProbe(): ((emoji: string) => boolean) | null {
    if (typeof document === "undefined") return null;
    try {
        const W = 32;
        const H = 32;
        const canvas = document.createElement("canvas");
        canvas.width = W * 2;
        canvas.height = H;
        const ctx = canvas.getContext("2d", { willReadFrequently: true });
        if (!ctx) return null;
        ctx.font = "20px sans-serif";
        ctx.textBaseline = "top";
        const refWidth = ctx.measureText("\u{1F600}").width || 20;
        return (emoji) => {
            ctx.clearRect(0, 0, W * 2, H);
            ctx.fillStyle = "#f00";
            ctx.fillText(emoji, 2, 4);
            ctx.fillStyle = "#00f";
            ctx.fillText(emoji, W + 2, 4);
            const a = ctx.getImageData(0, 0, W, H).data;
            let i = 0;
            while (i < a.length && a[i + 3] < VISIBLE_ALPHA) i += 4;
            if (i >= a.length) return false; // nothing drawn
            const px = (i / 4) % W;
            const py = Math.floor(i / 4 / W);
            const b = ctx.getImageData(W + px, py, 1, 1).data;
            if (
                Math.abs(a[i] - b[0]) > CHANNEL_TOLERANCE ||
                Math.abs(a[i + 2] - b[2]) > CHANNEL_TOLERANCE
            ) {
                return false; // took the fill colour → tofu or a monochrome fallback
            }
            return ctx.measureText(emoji).width < refWidth * 1.6; // split ZWJ sequence
        };
    } catch {
        return null;
    }
}

export function filterSupportedEmoji(
    entries: readonly EmojiEntry[],
    support: EmojiSupport
): EmojiEntry[] {
    return entries.filter(
        (e) => e.version <= support.maxVersion && (support.flags || !FLAG_SEQUENCE_RE.test(e.emoji))
    );
}
