import {
    Mail,
    Wallet,
    Target,
    FolderTree,
    Folder,
    CalendarDays,
    Home,
    Car,
    ShoppingCart,
    ShoppingBag,
    Utensils,
    Coffee,
    Gift,
    Plane,
    Heart,
    Bus,
    Fuel,
    Baby,
    GraduationCap,
    Stethoscope,
    Dumbbell,
    Film,
    Music,
    Gamepad2,
    BookOpen,
    Shirt,
    Cat,
    Landmark,
    Briefcase,
    PiggyBank,
    TrendingUp,
    TrendingDown,
    CreditCard,
    Banknote,
    Receipt,
    Hammer,
    Wrench,
    Zap,
    Droplets,
    Wifi,
    Phone,
    Cake,
    PartyPopper,
    Church,
    Baseline,
    // Money & finance extras
    Coins,
    HandCoins,
    Scale,
    Calculator,
    BadgePercent,
    ArrowRightLeft,
    DollarSign,
    Euro,
    PoundSterling,
    JapaneseYen,
    Bitcoin,
    CircleDollarSign,
    Vault,
    ChartLine,
    ChartPie,
    ChartBar,
    Wallet2,
    ReceiptText,
    // Home & bills extras
    House,
    Bed,
    Lamp,
    Sofa,
    Bath,
    WashingMachine,
    Refrigerator,
    Microwave,
    Plug,
    Flame,
    Smartphone,
    Tv,
    Key,
    Keyboard,
    Lightbulb,
    DoorOpen,
    // Food & drink extras
    Pizza,
    Wine,
    Beer,
    Carrot,
    Apple,
    Salad,
    IceCreamCone,
    Soup,
    Fish,
    Egg,
    Cookie,
    Croissant,
    Beef,
    Sandwich,
    CupSoda,
    Martini,
    Popcorn,
    Candy,
    Drumstick,
    // Shopping extras
    Store,
    Package,
    Tag,
    Tags,
    Box,
    ShoppingBasket,
    Barcode,
    QrCode,
    // Transport & travel extras
    Train,
    Bike,
    Ship,
    MapPin,
    Map,
    Compass,
    Truck,
    TramFront,
    Footprints,
    Luggage,
    Anchor,
    Sailboat,
    Rocket,
    CarTaxiFront,
    ParkingCircle,
    // Health & wellness extras
    HeartPulse,
    Pill,
    Syringe,
    Activity,
    Hospital,
    Cross,
    Bandage,
    // Education & work extras
    Book,
    Laptop,
    PenTool,
    Palette,
    Scissors,
    Ruler,
    Clipboard,
    FileText,
    Printer,
    Presentation,
    NotebookPen,
    PencilRuler,
    // Entertainment extras
    Headphones,
    Camera,
    Ticket,
    Drum,
    Guitar,
    Clapperboard,
    Radio,
    Dices,
    Puzzle,
    // Nature & pets extras
    Dog,
    Bird,
    PawPrint,
    TreeDeciduous,
    TreePine,
    Leaf,
    Flower,
    Flower2,
    Sun,
    Moon,
    Cloud,
    Mountain,
    Sprout,
    CloudRain,
    Snowflake,
    Rainbow,
    // People & social extras
    User,
    Users,
    UserPlus,
    Smile,
    HandHeart,
    // Tech & digital extras
    Monitor,
    Server,
    Database,
    Bug,
    Code,
    Bot,
    Mouse,
    Globe,
    Inbox,
    Send,
    MessageCircle,
    MessagesSquare,
    Rss,
    // Objects & misc extras
    Pencil,
    Bell,
    Star,
    Flag,
    Bookmark,
    Trophy,
    Award,
    Clock,
    Timer,
    Lock,
    Unlock,
    Shield,
    Watch,
    Paintbrush,
    Paperclip,
    Pin,
    Sticker,
    Sparkles,
    Bolt,
    Infinity as InfinityIcon,
    Recycle,
    Trash2,
    ListChecks,
    CheckCircle2,
    CircleHelp,
    AlertTriangle,
    // Work/office extras
    Building,
    Building2,
    Factory,
    Warehouse,
    HardHat,
    Hotel,
    School,
    LibraryBig,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type EntityIconCategory =
    | "Money"
    | "Home & Bills"
    | "Food & Drink"
    | "Shopping"
    | "Transport"
    | "Health"
    | "Work & Study"
    | "Entertainment"
    | "Nature & Pets"
    | "People"
    | "Tech"
    | "Places"
    | "Objects"
    | "Symbols";

/**
 * Curated icon catalog. The string name is what is persisted, so names in
 * this map MUST remain stable. Append new entries — do not rename existing
 * ones.
 */
export const ENTITY_ICONS: Record<string, LucideIcon> = {
    // --- Money & finance -------------------------------------------------
    wallet: Wallet,
    "wallet-2": Wallet2,
    "piggy-bank": PiggyBank,
    banknote: Banknote,
    coins: Coins,
    "hand-coins": HandCoins,
    "credit-card": CreditCard,
    landmark: Landmark,
    vault: Vault,
    receipt: Receipt,
    "receipt-text": ReceiptText,
    "trending-up": TrendingUp,
    "trending-down": TrendingDown,
    "chart-line": ChartLine,
    "chart-pie": ChartPie,
    "chart-bar": ChartBar,
    "circle-dollar-sign": CircleDollarSign,
    "dollar-sign": DollarSign,
    euro: Euro,
    "pound-sterling": PoundSterling,
    "japanese-yen": JapaneseYen,
    bitcoin: Bitcoin,
    scale: Scale,
    calculator: Calculator,
    "badge-percent": BadgePercent,
    "arrow-right-left": ArrowRightLeft,
    target: Target,

    // --- Home & bills ----------------------------------------------------
    home: Home,
    house: House,
    bed: Bed,
    sofa: Sofa,
    bath: Bath,
    lamp: Lamp,
    lightbulb: Lightbulb,
    "washing-machine": WashingMachine,
    refrigerator: Refrigerator,
    microwave: Microwave,
    "door-open": DoorOpen,
    key: Key,
    plug: Plug,
    zap: Zap,
    flame: Flame,
    droplets: Droplets,
    wifi: Wifi,
    phone: Phone,
    smartphone: Smartphone,
    tv: Tv,
    hammer: Hammer,
    wrench: Wrench,

    // --- Food & drink ----------------------------------------------------
    utensils: Utensils,
    coffee: Coffee,
    pizza: Pizza,
    wine: Wine,
    beer: Beer,
    martini: Martini,
    "cup-soda": CupSoda,
    carrot: Carrot,
    apple: Apple,
    salad: Salad,
    soup: Soup,
    fish: Fish,
    egg: Egg,
    cookie: Cookie,
    cake: Cake,
    croissant: Croissant,
    beef: Beef,
    sandwich: Sandwich,
    popcorn: Popcorn,
    candy: Candy,
    drumstick: Drumstick,
    "ice-cream-cone": IceCreamCone,

    // --- Shopping --------------------------------------------------------
    "shopping-cart": ShoppingCart,
    "shopping-bag": ShoppingBag,
    "shopping-basket": ShoppingBasket,
    store: Store,
    package: Package,
    box: Box,
    gift: Gift,
    shirt: Shirt,
    tag: Tag,
    tags: Tags,
    barcode: Barcode,
    "qr-code": QrCode,

    // --- Transport & travel ---------------------------------------------
    car: Car,
    "car-taxi": CarTaxiFront,
    bus: Bus,
    tram: TramFront,
    train: Train,
    bike: Bike,
    plane: Plane,
    ship: Ship,
    sailboat: Sailboat,
    rocket: Rocket,
    truck: Truck,
    fuel: Fuel,
    "parking-circle": ParkingCircle,
    footprints: Footprints,
    luggage: Luggage,
    anchor: Anchor,
    compass: Compass,
    map: Map,
    "map-pin": MapPin,

    // --- Health & wellness ----------------------------------------------
    heart: Heart,
    "heart-pulse": HeartPulse,
    stethoscope: Stethoscope,
    pill: Pill,
    syringe: Syringe,
    bandage: Bandage,
    activity: Activity,
    hospital: Hospital,
    cross: Cross,
    dumbbell: Dumbbell,
    baby: Baby,

    // --- Work & study ---------------------------------------------------
    briefcase: Briefcase,
    "graduation-cap": GraduationCap,
    "book-open": BookOpen,
    book: Book,
    laptop: Laptop,
    "pen-tool": PenTool,
    palette: Palette,
    scissors: Scissors,
    ruler: Ruler,
    "pencil-ruler": PencilRuler,
    pencil: Pencil,
    clipboard: Clipboard,
    "file-text": FileText,
    "notebook-pen": NotebookPen,
    printer: Printer,
    presentation: Presentation,
    folder: Folder,
    "folder-tree": FolderTree,

    // --- Entertainment --------------------------------------------------
    film: Film,
    music: Music,
    "gamepad-2": Gamepad2,
    headphones: Headphones,
    camera: Camera,
    ticket: Ticket,
    drum: Drum,
    guitar: Guitar,
    clapperboard: Clapperboard,
    radio: Radio,
    dices: Dices,
    puzzle: Puzzle,
    "party-popper": PartyPopper,

    // --- Nature & pets --------------------------------------------------
    cat: Cat,
    dog: Dog,
    bird: Bird,
    "paw-print": PawPrint,
    "tree-deciduous": TreeDeciduous,
    "tree-pine": TreePine,
    leaf: Leaf,
    flower: Flower,
    "flower-2": Flower2,
    sprout: Sprout,
    sun: Sun,
    moon: Moon,
    cloud: Cloud,
    "cloud-rain": CloudRain,
    snowflake: Snowflake,
    rainbow: Rainbow,
    mountain: Mountain,

    // --- People ---------------------------------------------------------
    user: User,
    users: Users,
    "user-plus": UserPlus,
    smile: Smile,
    "hand-heart": HandHeart,

    // --- Tech & digital -------------------------------------------------
    monitor: Monitor,
    keyboard: Keyboard,
    mouse: Mouse,
    server: Server,
    database: Database,
    bug: Bug,
    code: Code,
    bot: Bot,
    globe: Globe,
    mail: Mail,
    inbox: Inbox,
    send: Send,
    "message-circle": MessageCircle,
    "messages-square": MessagesSquare,
    rss: Rss,

    // --- Places ---------------------------------------------------------
    building: Building,
    "building-2": Building2,
    factory: Factory,
    warehouse: Warehouse,
    hotel: Hotel,
    school: School,
    library: LibraryBig,
    church: Church,
    "hard-hat": HardHat,

    // --- Objects --------------------------------------------------------
    bell: Bell,
    star: Star,
    flag: Flag,
    bookmark: Bookmark,
    trophy: Trophy,
    award: Award,
    "calendar-days": CalendarDays,
    clock: Clock,
    timer: Timer,
    lock: Lock,
    unlock: Unlock,
    shield: Shield,
    watch: Watch,
    paintbrush: Paintbrush,
    paperclip: Paperclip,
    pin: Pin,
    sticker: Sticker,

    // --- Symbols --------------------------------------------------------
    sparkles: Sparkles,
    bolt: Bolt,
    infinity: InfinityIcon,
    recycle: Recycle,
    "trash-2": Trash2,
    "list-checks": ListChecks,
    "check-circle-2": CheckCircle2,
    "circle-help": CircleHelp,
    "alert-triangle": AlertTriangle,
};

export const ENTITY_ICON_NAMES = Object.keys(ENTITY_ICONS);

/**
 * Ordered category grouping for the picker UI. Every name in
 * `ENTITY_ICONS` must appear in exactly one category.
 */
export const ENTITY_ICON_CATEGORIES: { label: EntityIconCategory; names: string[] }[] = [
    {
        label: "Money",
        names: [
            "wallet",
            "wallet-2",
            "piggy-bank",
            "banknote",
            "coins",
            "hand-coins",
            "credit-card",
            "landmark",
            "vault",
            "receipt",
            "receipt-text",
            "trending-up",
            "trending-down",
            "chart-line",
            "chart-pie",
            "chart-bar",
            "circle-dollar-sign",
            "dollar-sign",
            "euro",
            "pound-sterling",
            "japanese-yen",
            "bitcoin",
            "scale",
            "calculator",
            "badge-percent",
            "arrow-right-left",
            "target",
        ],
    },
    {
        label: "Home & Bills",
        names: [
            "home",
            "house",
            "bed",
            "sofa",
            "bath",
            "lamp",
            "lightbulb",
            "washing-machine",
            "refrigerator",
            "microwave",
            "door-open",
            "key",
            "plug",
            "zap",
            "flame",
            "droplets",
            "wifi",
            "phone",
            "smartphone",
            "tv",
            "hammer",
            "wrench",
        ],
    },
    {
        label: "Food & Drink",
        names: [
            "utensils",
            "coffee",
            "pizza",
            "wine",
            "beer",
            "martini",
            "cup-soda",
            "carrot",
            "apple",
            "salad",
            "soup",
            "fish",
            "egg",
            "cookie",
            "cake",
            "croissant",
            "beef",
            "sandwich",
            "popcorn",
            "candy",
            "drumstick",
            "ice-cream-cone",
        ],
    },
    {
        label: "Shopping",
        names: [
            "shopping-cart",
            "shopping-bag",
            "shopping-basket",
            "store",
            "package",
            "box",
            "gift",
            "shirt",
            "tag",
            "tags",
            "barcode",
            "qr-code",
        ],
    },
    {
        label: "Transport",
        names: [
            "car",
            "car-taxi",
            "bus",
            "tram",
            "train",
            "bike",
            "plane",
            "ship",
            "sailboat",
            "rocket",
            "truck",
            "fuel",
            "parking-circle",
            "footprints",
            "luggage",
            "anchor",
            "compass",
            "map",
            "map-pin",
        ],
    },
    {
        label: "Health",
        names: [
            "heart",
            "heart-pulse",
            "stethoscope",
            "pill",
            "syringe",
            "bandage",
            "activity",
            "hospital",
            "cross",
            "dumbbell",
            "baby",
        ],
    },
    {
        label: "Work & Study",
        names: [
            "briefcase",
            "graduation-cap",
            "book-open",
            "book",
            "laptop",
            "pen-tool",
            "palette",
            "scissors",
            "ruler",
            "pencil-ruler",
            "pencil",
            "clipboard",
            "file-text",
            "notebook-pen",
            "printer",
            "presentation",
            "folder",
            "folder-tree",
        ],
    },
    {
        label: "Entertainment",
        names: [
            "film",
            "music",
            "gamepad-2",
            "headphones",
            "camera",
            "ticket",
            "drum",
            "guitar",
            "clapperboard",
            "radio",
            "dices",
            "puzzle",
            "party-popper",
        ],
    },
    {
        label: "Nature & Pets",
        names: [
            "cat",
            "dog",
            "bird",
            "paw-print",
            "tree-deciduous",
            "tree-pine",
            "leaf",
            "flower",
            "flower-2",
            "sprout",
            "sun",
            "moon",
            "cloud",
            "cloud-rain",
            "snowflake",
            "rainbow",
            "mountain",
        ],
    },
    {
        label: "People",
        names: ["user", "users", "user-plus", "smile", "hand-heart"],
    },
    {
        label: "Tech",
        names: [
            "monitor",
            "keyboard",
            "mouse",
            "server",
            "database",
            "bug",
            "code",
            "bot",
            "globe",
            "mail",
            "inbox",
            "send",
            "message-circle",
            "messages-square",
            "rss",
        ],
    },
    {
        label: "Places",
        names: [
            "building",
            "building-2",
            "factory",
            "warehouse",
            "hotel",
            "school",
            "library",
            "church",
            "hard-hat",
        ],
    },
    {
        label: "Objects",
        names: [
            "bell",
            "star",
            "flag",
            "bookmark",
            "trophy",
            "award",
            "calendar-days",
            "clock",
            "timer",
            "lock",
            "unlock",
            "shield",
            "watch",
            "paintbrush",
            "paperclip",
            "pin",
            "sticker",
        ],
    },
    {
        label: "Symbols",
        names: [
            "sparkles",
            "bolt",
            "infinity",
            "recycle",
            "trash-2",
            "list-checks",
            "check-circle-2",
            "circle-help",
            "alert-triangle",
        ],
    },
];

/** Resolve a persisted icon name to a component, with a safe fallback. */
export function getIcon(
    name: string | null | undefined,
    fallback: LucideIcon = Baseline
): LucideIcon {
    if (!name) return fallback;
    return ENTITY_ICONS[name] ?? fallback;
}
