import {
    Mail,
    Wallet,
    Target,
    FolderTree,
    Folder,
    CalendarDays,
    Home,
    Car,
    ShoppingCart,
    ShoppingBag,
    Utensils,
    Coffee,
    Gift,
    Plane,
    Heart,
    Bus,
    Fuel,
    Baby,
    GraduationCap,
    Stethoscope,
    Dumbbell,
    Film,
    Music,
    Gamepad2,
    BookOpen,
    Shirt,
    Cat,
    Landmark,
    Briefcase,
    PiggyBank,
    TrendingUp,
    TrendingDown,
    CreditCard,
    Banknote,
    Receipt,
    Hammer,
    Wrench,
    Zap,
    Droplets,
    Wifi,
    Phone,
    Cake,
    PartyPopper,
    Church,
    Baseline,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

/** Curated icon catalog. The string name is what is persisted. */
export const ENTITY_ICONS: Record<string, LucideIcon> = {
    mail: Mail,
    wallet: Wallet,
    target: Target,
    "folder-tree": FolderTree,
    folder: Folder,
    "calendar-days": CalendarDays,
    home: Home,
    car: Car,
    "shopping-cart": ShoppingCart,
    "shopping-bag": ShoppingBag,
    utensils: Utensils,
    coffee: Coffee,
    gift: Gift,
    plane: Plane,
    heart: Heart,
    bus: Bus,
    fuel: Fuel,
    baby: Baby,
    "graduation-cap": GraduationCap,
    stethoscope: Stethoscope,
    dumbbell: Dumbbell,
    film: Film,
    music: Music,
    "gamepad-2": Gamepad2,
    "book-open": BookOpen,
    shirt: Shirt,
    cat: Cat,
    landmark: Landmark,
    briefcase: Briefcase,
    "piggy-bank": PiggyBank,
    "trending-up": TrendingUp,
    "trending-down": TrendingDown,
    "credit-card": CreditCard,
    banknote: Banknote,
    receipt: Receipt,
    hammer: Hammer,
    wrench: Wrench,
    zap: Zap,
    droplets: Droplets,
    wifi: Wifi,
    phone: Phone,
    cake: Cake,
    "party-popper": PartyPopper,
    church: Church,
};

export const ENTITY_ICON_NAMES = Object.keys(ENTITY_ICONS);

/** Resolve a persisted icon name to a component, with a safe fallback. */
export function getIcon(name: string | null | undefined, fallback: LucideIcon = Baseline): LucideIcon {
    if (!name) return fallback;
    return ENTITY_ICONS[name] ?? fallback;
}
