import type { ComponentType, FunctionComponent, SVGProps } from "react";
import { createElement } from "react";
import type { LucideIcon } from "lucide-react";
import {
    Accessibility,
    Activity,
    AirVent,
    Airplay,
    AlarmClock,
    AlertTriangle,
    Ambulance,
    Anchor,
    Angry,
    Annoyed,
    Antenna,
    Anvil,
    AppWindow,
    Apple,
    Archive,
    Armchair,
    ArrowRightLeft,
    Asterisk,
    AtSign,
    Atom,
    Award,
    Axe,
    Baby,
    Backpack,
    Badge,
    BadgeCheck,
    BadgeDollarSign,
    BadgePercent,
    BaggageClaim,
    Balloon,
    Ban,
    Banana,
    Bandage,
    Banknote,
    BanknoteArrowDown,
    BanknoteArrowUp,
    Barcode,
    Barrel,
    Baseline,
    Bath,
    Battery,
    BatteryCharging,
    Beaker,
    Bean,
    Bed,
    BedDouble,
    Beef,
    Beer,
    Bell,
    BellRing,
    BicepsFlexed,
    Bike,
    Binary,
    Binoculars,
    Biohazard,
    Bird,
    Birdhouse,
    Bitcoin,
    Blinds,
    Blocks,
    Bluetooth,
    Bolt,
    Bomb,
    Bone,
    Book,
    BookA,
    BookHeart,
    BookMarked,
    BookOpen,
    BookText,
    Bookmark,
    BoomBox,
    Bot,
    BottleWine,
    BowArrow,
    Box,
    Boxes,
    Braces,
    Brain,
    BrainCircuit,
    BrickWall,
    Briefcase,
    BriefcaseBusiness,
    BriefcaseMedical,
    Brush,
    BrushCleaning,
    Bug,
    Building,
    Building2,
    Bus,
    BusFront,
    Cable,
    CableCar,
    Cake,
    CakeSlice,
    Calculator,
    Calendar,
    CalendarClock,
    CalendarDays,
    CalendarHeart,
    CalendarRange,
    CalendarSync,
    Camera,
    Candy,
    CandyCane,
    Car,
    CarFront,
    CarTaxiFront,
    Caravan,
    Carrot,
    CassetteTape,
    Cast,
    Castle,
    Cat,
    Cctv,
    ChartArea,
    ChartBar,
    ChartCandlestick,
    ChartColumn,
    ChartLine,
    ChartNoAxesCombined,
    ChartPie,
    ChartSpline,
    Check,
    CheckCheck,
    CheckCircle2,
    ChefHat,
    Cherry,
    ChessKing,
    ChessKnight,
    ChessQueen,
    Church,
    Cigarette,
    CigaretteOff,
    Circle,
    CircleAlert,
    CircleDollarSign,
    CircleHelp,
    CirclePercent,
    CircleUserRound,
    CircuitBoard,
    Citrus,
    Clapperboard,
    Clipboard,
    Clock,
    Cloud,
    CloudDownload,
    CloudFog,
    CloudLightning,
    CloudRain,
    CloudSnow,
    CloudSun,
    CloudUpload,
    Clover,
    Club,
    Code,
    Coffee,
    Cog,
    Coins,
    Command,
    Compass,
    ConciergeBell,
    Construction,
    Contact,
    Container,
    Cookie,
    CookingPot,
    Copyright,
    Cpu,
    CreditCard,
    Croissant,
    Cross,
    Crown,
    CupSoda,
    Currency,
    Dam,
    Database,
    Dessert,
    Diamond,
    Dices,
    Disc,
    Disc3,
    DiscAlbum,
    Divide,
    Dna,
    Dog,
    DollarSign,
    Donut,
    DoorClosed,
    DoorOpen,
    DraftingCompass,
    Drama,
    Drill,
    Drone,
    Droplet,
    Droplets,
    Drum,
    Drumstick,
    Dumbbell,
    Ear,
    Earth,
    Eclipse,
    Egg,
    EggFried,
    Equal,
    Eraser,
    Euro,
    EvCharger,
    Eye,
    Factory,
    Fan,
    Feather,
    Fence,
    FerrisWheel,
    FileBadge,
    FileChartColumn,
    FileSignature,
    FileSpreadsheet,
    FileText,
    Files,
    Film,
    Fingerprint,
    Fish,
    FishSymbol,
    Flag,
    FlagTriangleRight,
    Flame,
    Flashlight,
    FlaskConical,
    Flower,
    Flower2,
    Folder,
    FolderTree,
    Footprints,
    Forklift,
    Frown,
    Fuel,
    Gamepad,
    Gamepad2,
    Gavel,
    Gem,
    Ghost,
    Gift,
    GitBranch,
    GlassWater,
    Glasses,
    Globe,
    Goal,
    Gpu,
    GraduationCap,
    Grape,
    Guitar,
    Ham,
    Hamburger,
    Hammer,
    Hand,
    HandCoins,
    HandFist,
    HandHeart,
    HandHelping,
    HandMetal,
    HandPlatter,
    Handbag,
    Handshake,
    HardDrive,
    HardHat,
    Hash,
    HatGlasses,
    Haze,
    Headphones,
    Headset,
    Heart,
    HeartCrack,
    HeartHandshake,
    HeartPulse,
    Heater,
    Helicopter,
    Hexagon,
    Highlighter,
    History as HistoryIcon,
    Home,
    Hop,
    Hospital,
    Hotel,
    Hourglass,
    House,
    HouseHeart,
    HousePlug,
    HousePlus,
    HouseWifi,
    IceCreamBowl,
    IceCreamCone,
    IdCard,
    Image as ImageIcon,
    Images,
    Inbox,
    IndianRupee,
    Infinity as InfinityIcon,
    Info,
    JapaneseYen,
    Joystick,
    Kanban,
    Kayak,
    Key,
    KeyRound,
    Keyboard,
    KeyboardMusic,
    Lamp,
    LampCeiling,
    LampDesk,
    LampFloor,
    LandPlot,
    Landmark,
    Languages,
    Laptop,
    Laugh,
    Layers,
    LayoutDashboard,
    Leaf,
    LeafyGreen,
    Lectern,
    LibraryBig,
    LifeBuoy,
    Lightbulb,
    ListChecks,
    ListMusic,
    Lock,
    LockKeyhole,
    Lollipop,
    Luggage,
    Magnet,
    Mail,
    Mailbox,
    Map as MapIcon,
    MapPin,
    MapPinHouse,
    MapPinned,
    Mars,
    Martini,
    Medal,
    Megaphone,
    Meh,
    MemoryStick,
    MessageCircle,
    MessagesSquare,
    Metronome,
    Mic,
    MicVocal,
    Microchip,
    Microscope,
    Microwave,
    Milestone,
    Milk,
    Minus,
    Monitor,
    Moon,
    MoonStar,
    Motorbike,
    Mountain,
    MountainSnow,
    Mouse,
    Music,
    Navigation,
    Network,
    Newspaper,
    Nfc,
    NonBinary,
    Notebook,
    NotebookPen,
    NotebookTabs,
    NotepadText,
    Nut,
    Octagon,
    Omega,
    Orbit,
    Origami,
    Package,
    PackageCheck,
    PackageOpen,
    PackageSearch,
    PaintBucket,
    PaintRoller,
    Paintbrush,
    Palette,
    Panda,
    Paperclip,
    ParkingCircle,
    ParkingMeter,
    PartyPopper,
    PawPrint,
    PcCase,
    Pen,
    PenLine,
    PenTool,
    Pencil,
    PencilRuler,
    Pentagon,
    Percent,
    PersonStanding,
    Phone,
    Pi,
    Piano,
    Pickaxe,
    PiggyBank,
    Pill,
    PillBottle,
    Pin,
    Pipette,
    Pizza,
    Plane,
    PlaneLanding,
    PlaneTakeoff,
    Plug,
    PlugZap,
    Plus,
    PocketKnife,
    Podcast,
    Popcorn,
    Popsicle,
    PoundSterling,
    Power,
    Presentation,
    Printer,
    Projector,
    Puzzle,
    Pyramid,
    QrCode,
    Rabbit,
    Radiation,
    Radio,
    RadioTower,
    Rainbow,
    Rat,
    Receipt,
    ReceiptText,
    Recycle,
    Refrigerator,
    Repeat,
    Ribbon,
    Road,
    Rocket,
    RollerCoaster,
    Rose,
    Route,
    Router,
    Rss,
    Ruler,
    Sailboat,
    Salad,
    Sandwich,
    Satellite,
    SatelliteDish,
    Scale,
    ScanBarcode,
    ScanHeart,
    School,
    Scissors,
    Scooter,
    Scroll,
    ScrollText,
    Send,
    Server,
    Shapes,
    Shell,
    ShelvingUnit,
    Shield,
    ShieldCheck,
    Ship,
    ShipWheel,
    Shirt,
    ShoppingBag,
    ShoppingBasket,
    ShoppingCart,
    Shovel,
    ShowerHead,
    Shrimp,
    Shrub,
    Sigma,
    Signal,
    Signature,
    Signpost,
    Skull,
    Smartphone,
    SmartphoneCharging,
    SmartphoneNfc,
    Smile,
    Snail,
    Snowflake,
    SoapDispenserDroplet,
    Sofa,
    SolarPanel,
    Soup,
    Spade,
    Sparkle,
    Sparkles,
    Speaker,
    Speech,
    Spool,
    SportShoe,
    SprayCan,
    Sprout,
    Square,
    Squirrel,
    Stamp,
    Star,
    Stethoscope,
    Sticker,
    Stone,
    Store,
    Sun,
    Sunrise,
    Sunset,
    SwatchBook,
    Sword,
    Swords,
    Syringe,
    Tablet,
    TabletSmartphone,
    Tablets,
    Tag,
    Tags,
    Target,
    Telescope,
    Tent,
    TentTree,
    Terminal,
    TestTube,
    Theater,
    Thermometer,
    ThumbsDown,
    ThumbsUp,
    Ticket,
    TicketPercent,
    Tickets,
    TicketsPlane,
    Timer,
    Toilet,
    ToolCase,
    Toolbox,
    Tornado,
    TowelRack,
    TowerControl,
    ToyBrick,
    Tractor,
    TrafficCone,
    Train,
    TrainFront,
    TrainTrack,
    TramFront,
    Transgender,
    Trash,
    Trash2,
    TreeDeciduous,
    TreePalm,
    TreePine,
    Trees,
    TrendingDown,
    TrendingUp,
    TrendingUpDown,
    Triangle,
    Trophy,
    Truck,
    TruckElectric,
    Turntable,
    Turtle,
    Tv,
    TvMinimalPlay,
    Umbrella,
    University,
    Unlock,
    Unplug,
    Usb,
    User,
    UserCheck,
    UserCog,
    UserPlus,
    UserRound,
    UserStar,
    Users,
    UsersRound,
    Utensils,
    UtensilsCrossed,
    UtilityPole,
    Van,
    Vault,
    Vegan,
    VenetianMask,
    Venus,
    VenusAndMars,
    Video,
    Videotape,
    Volleyball,
    Wallet,
    Wallet2,
    WalletCards,
    Wand,
    WandSparkles,
    Warehouse,
    WashingMachine,
    Watch,
    Waves,
    Webcam,
    Webhook,
    Weight,
    Wheat,
    Wifi,
    Wind,
    Wine,
    Worm,
    Wrench,
    X,
    Zap,
} from "lucide-react";
import { EmojiGlyph } from "@/components/shared/EmojiGlyph";
import { isEmojiIcon } from "@/lib/emoji";

/**
 * Props every entity icon accepts, whether it resolves to a Lucide icon or an
 * emoji. Size it with a class (`<Icon className="size-4" />`) exactly like a
 * Lucide icon — the emoji renderer scales the same way.
 */
export type EntityIconProps = Pick<
    SVGProps<SVGSVGElement>,
    "className" | "color" | "strokeWidth" | "aria-hidden" | "aria-label" | "role"
> & {
    /** Pixel size shorthand, as on Lucide icons — a size-* class still wins. */
    size?: number | string;
};
export type EntityIconComponent = ComponentType<EntityIconProps>;

export type EntityIconCategory =
    | "Money"
    | "Home & Bills"
    | "Food & Drink"
    | "Shopping"
    | "Transport"
    | "Health"
    | "Work & Study"
    | "Entertainment"
    | "Nature & Pets"
    | "People"
    | "Tech"
    | "Places"
    | "Objects"
    | "Symbols";

interface IconCategoryDef {
    label: EntityIconCategory;
    /** Registry key of the icon that represents the category in the picker's category strip. */
    icon: string;
    icons: Record<string, LucideIcon>;
}

/**
 * Curated Lucide catalog, grouped for the picker. A persisted icon value is
 * either one of these keys or a raw emoji string (see `lib/emoji.ts`);
 * `getIcon()` resolves both.
 *
 * Keys are what gets persisted on envelopes / accounts / categories / events,
 * so they MUST remain stable: append new entries, never rename or remove
 * existing ones. Categories are presentation only and may be reshuffled
 * freely, but each key may appear in exactly one of them (`Object.assign`
 * below would silently collapse duplicates — `pnpm generate-icons` asserts
 * this). Search tags for these keys come from lucide-static and are
 * generated into `icons/lucide-tags.generated.json`; rerun
 * `pnpm generate-icons` after adding icons here.
 */
const CATEGORIES: readonly IconCategoryDef[] = [
    {
        label: "Money",
        icon: "wallet",
        icons: {
            wallet: Wallet,
            "wallet-2": Wallet2,
            "wallet-cards": WalletCards,
            mail: Mail,
            "piggy-bank": PiggyBank,
            vault: Vault,
            target: Target,
            goal: Goal,
            banknote: Banknote,
            "banknote-arrow-up": BanknoteArrowUp,
            "banknote-arrow-down": BanknoteArrowDown,
            coins: Coins,
            "hand-coins": HandCoins,
            "credit-card": CreditCard,
            landmark: Landmark,
            receipt: Receipt,
            "receipt-text": ReceiptText,
            calculator: Calculator,
            scale: Scale,
            gavel: Gavel,
            handshake: Handshake,
            "arrow-right-left": ArrowRightLeft,
            repeat: Repeat,
            percent: Percent,
            "circle-percent": CirclePercent,
            "badge-percent": BadgePercent,
            currency: Currency,
            "circle-dollar-sign": CircleDollarSign,
            "badge-dollar-sign": BadgeDollarSign,
            "dollar-sign": DollarSign,
            euro: Euro,
            "pound-sterling": PoundSterling,
            "japanese-yen": JapaneseYen,
            "indian-rupee": IndianRupee,
            bitcoin: Bitcoin,
            gem: Gem,
            "trending-up": TrendingUp,
            "trending-down": TrendingDown,
            "trending-up-down": TrendingUpDown,
            "chart-line": ChartLine,
            "chart-pie": ChartPie,
            "chart-bar": ChartBar,
            "chart-column": ChartColumn,
            "chart-area": ChartArea,
            "chart-spline": ChartSpline,
            "chart-candlestick": ChartCandlestick,
            "chart-no-axes-combined": ChartNoAxesCombined,
        },
    },
    {
        label: "Home & Bills",
        icon: "house",
        icons: {
            house: House,
            "house-plus": HousePlus,
            "house-heart": HouseHeart,
            "house-plug": HousePlug,
            "house-wifi": HouseWifi,
            bed: Bed,
            "bed-double": BedDouble,
            sofa: Sofa,
            armchair: Armchair,
            bath: Bath,
            "shower-head": ShowerHead,
            toilet: Toilet,
            "towel-rack": TowelRack,
            lamp: Lamp,
            "lamp-ceiling": LampCeiling,
            "lamp-desk": LampDesk,
            "lamp-floor": LampFloor,
            lightbulb: Lightbulb,
            blinds: Blinds,
            fan: Fan,
            heater: Heater,
            "air-vent": AirVent,
            "washing-machine": WashingMachine,
            refrigerator: Refrigerator,
            microwave: Microwave,
            "cooking-pot": CookingPot,
            "shelving-unit": ShelvingUnit,
            "door-open": DoorOpen,
            "door-closed": DoorClosed,
            key: Key,
            "key-round": KeyRound,
            mailbox: Mailbox,
            fence: Fence,
            "brick-wall": BrickWall,
            plug: Plug,
            "plug-zap": PlugZap,
            unplug: Unplug,
            cable: Cable,
            zap: Zap,
            "solar-panel": SolarPanel,
            "utility-pole": UtilityPole,
            flame: Flame,
            thermometer: Thermometer,
            droplets: Droplets,
            droplet: Droplet,
            waves: Waves,
            wifi: Wifi,
            phone: Phone,
            smartphone: Smartphone,
            tv: Tv,
            hammer: Hammer,
            wrench: Wrench,
            drill: Drill,
            axe: Axe,
            shovel: Shovel,
            "paint-roller": PaintRoller,
            "paint-bucket": PaintBucket,
            brush: Brush,
            paintbrush: Paintbrush,
            "brush-cleaning": BrushCleaning,
            "soap-dispenser-droplet": SoapDispenserDroplet,
            trash: Trash,
            "trash-2": Trash2,
            toolbox: Toolbox,
            "tool-case": ToolCase,
            cog: Cog,
            flashlight: Flashlight,
        },
    },
    {
        label: "Food & Drink",
        icon: "utensils",
        icons: {
            utensils: Utensils,
            "utensils-crossed": UtensilsCrossed,
            "chef-hat": ChefHat,
            "hand-platter": HandPlatter,
            "concierge-bell": ConciergeBell,
            coffee: Coffee,
            "cup-soda": CupSoda,
            "glass-water": GlassWater,
            milk: Milk,
            wine: Wine,
            "bottle-wine": BottleWine,
            beer: Beer,
            hop: Hop,
            martini: Martini,
            barrel: Barrel,
            pizza: Pizza,
            hamburger: Hamburger,
            sandwich: Sandwich,
            ham: Ham,
            beef: Beef,
            drumstick: Drumstick,
            fish: Fish,
            shrimp: Shrimp,
            egg: Egg,
            "egg-fried": EggFried,
            soup: Soup,
            salad: Salad,
            "leafy-green": LeafyGreen,
            vegan: Vegan,
            carrot: Carrot,
            bean: Bean,
            wheat: Wheat,
            apple: Apple,
            banana: Banana,
            cherry: Cherry,
            citrus: Citrus,
            grape: Grape,
            nut: Nut,
            cookie: Cookie,
            croissant: Croissant,
            cake: Cake,
            "cake-slice": CakeSlice,
            dessert: Dessert,
            donut: Donut,
            "ice-cream-cone": IceCreamCone,
            "ice-cream-bowl": IceCreamBowl,
            popsicle: Popsicle,
            candy: Candy,
            "candy-cane": CandyCane,
            lollipop: Lollipop,
            popcorn: Popcorn,
        },
    },
    {
        label: "Shopping",
        icon: "shopping-cart",
        icons: {
            "shopping-cart": ShoppingCart,
            "shopping-bag": ShoppingBag,
            "shopping-basket": ShoppingBasket,
            store: Store,
            handbag: Handbag,
            package: Package,
            "package-open": PackageOpen,
            "package-check": PackageCheck,
            "package-search": PackageSearch,
            box: Box,
            boxes: Boxes,
            container: Container,
            gift: Gift,
            ribbon: Ribbon,
            shirt: Shirt,
            "sport-shoe": SportShoe,
            glasses: Glasses,
            "hat-glasses": HatGlasses,
            tag: Tag,
            tags: Tags,
            ticket: Ticket,
            tickets: Tickets,
            "ticket-percent": TicketPercent,
            barcode: Barcode,
            "scan-barcode": ScanBarcode,
            "qr-code": QrCode,
            "spray-can": SprayCan,
            "swatch-book": SwatchBook,
            spool: Spool,
        },
    },
    {
        label: "Transport",
        icon: "car",
        icons: {
            car: Car,
            "car-front": CarFront,
            "car-taxi": CarTaxiFront,
            caravan: Caravan,
            van: Van,
            truck: Truck,
            "truck-electric": TruckElectric,
            tractor: Tractor,
            forklift: Forklift,
            bus: Bus,
            "bus-front": BusFront,
            tram: TramFront,
            "train-front": TrainFront,
            "train-track": TrainTrack,
            "cable-car": CableCar,
            bike: Bike,
            motorbike: Motorbike,
            scooter: Scooter,
            plane: Plane,
            "plane-takeoff": PlaneTakeoff,
            "plane-landing": PlaneLanding,
            "tickets-plane": TicketsPlane,
            helicopter: Helicopter,
            drone: Drone,
            rocket: Rocket,
            ship: Ship,
            "ship-wheel": ShipWheel,
            sailboat: Sailboat,
            kayak: Kayak,
            anchor: Anchor,
            fuel: Fuel,
            "ev-charger": EvCharger,
            "parking-circle": ParkingCircle,
            "parking-meter": ParkingMeter,
            "traffic-cone": TrafficCone,
            road: Road,
            route: Route,
            milestone: Milestone,
            signpost: Signpost,
            navigation: Navigation,
            compass: Compass,
            map: MapIcon,
            "map-pin": MapPin,
            "map-pinned": MapPinned,
            "map-pin-house": MapPinHouse,
            earth: Earth,
            footprints: Footprints,
            luggage: Luggage,
            "baggage-claim": BaggageClaim,
        },
    },
    {
        label: "Health",
        icon: "heart-pulse",
        icons: {
            heart: Heart,
            "heart-pulse": HeartPulse,
            "heart-handshake": HeartHandshake,
            "heart-crack": HeartCrack,
            "scan-heart": ScanHeart,
            stethoscope: Stethoscope,
            "briefcase-medical": BriefcaseMedical,
            ambulance: Ambulance,
            hospital: Hospital,
            cross: Cross,
            pill: Pill,
            "pill-bottle": PillBottle,
            tablets: Tablets,
            syringe: Syringe,
            bandage: Bandage,
            activity: Activity,
            brain: Brain,
            bone: Bone,
            ear: Ear,
            eye: Eye,
            dna: Dna,
            microscope: Microscope,
            "test-tube": TestTube,
            "flask-conical": FlaskConical,
            beaker: Beaker,
            dumbbell: Dumbbell,
            "biceps-flexed": BicepsFlexed,
            weight: Weight,
            "person-standing": PersonStanding,
            accessibility: Accessibility,
            cigarette: Cigarette,
            "cigarette-off": CigaretteOff,
        },
    },
    {
        label: "Work & Study",
        icon: "briefcase",
        icons: {
            briefcase: Briefcase,
            "briefcase-business": BriefcaseBusiness,
            "graduation-cap": GraduationCap,
            university: University,
            backpack: Backpack,
            "book-open": BookOpen,
            book: Book,
            "book-text": BookText,
            "book-marked": BookMarked,
            "book-heart": BookHeart,
            "book-a": BookA,
            languages: Languages,
            notebook: Notebook,
            "notebook-pen": NotebookPen,
            "notebook-tabs": NotebookTabs,
            "notepad-text": NotepadText,
            laptop: Laptop,
            "pen-tool": PenTool,
            pen: Pen,
            "pen-line": PenLine,
            pencil: Pencil,
            "pencil-ruler": PencilRuler,
            highlighter: Highlighter,
            eraser: Eraser,
            ruler: Ruler,
            "drafting-compass": DraftingCompass,
            scissors: Scissors,
            palette: Palette,
            feather: Feather,
            stamp: Stamp,
            signature: Signature,
            clipboard: Clipboard,
            "file-text": FileText,
            "file-spreadsheet": FileSpreadsheet,
            "file-chart-column": FileChartColumn,
            "file-signature": FileSignature,
            "file-badge": FileBadge,
            files: Files,
            archive: Archive,
            folder: Folder,
            "folder-tree": FolderTree,
            newspaper: Newspaper,
            scroll: Scroll,
            "scroll-text": ScrollText,
            printer: Printer,
            presentation: Presentation,
            projector: Projector,
            lectern: Lectern,
            kanban: Kanban,
            "layout-dashboard": LayoutDashboard,
            megaphone: Megaphone,
            speech: Speech,
            construction: Construction,
            "hard-hat": HardHat,
            anvil: Anvil,
            pickaxe: Pickaxe,
            telescope: Telescope,
        },
    },
    {
        label: "Entertainment",
        icon: "gamepad-2",
        icons: {
            film: Film,
            clapperboard: Clapperboard,
            video: Video,
            videotape: Videotape,
            "tv-minimal-play": TvMinimalPlay,
            music: Music,
            "list-music": ListMusic,
            headphones: Headphones,
            speaker: Speaker,
            "boom-box": BoomBox,
            radio: Radio,
            podcast: Podcast,
            mic: Mic,
            "mic-vocal": MicVocal,
            "disc-3": Disc3,
            "disc-album": DiscAlbum,
            turntable: Turntable,
            "cassette-tape": CassetteTape,
            guitar: Guitar,
            piano: Piano,
            drum: Drum,
            "keyboard-music": KeyboardMusic,
            metronome: Metronome,
            "gamepad-2": Gamepad2,
            gamepad: Gamepad,
            joystick: Joystick,
            dices: Dices,
            puzzle: Puzzle,
            "chess-king": ChessKing,
            "chess-queen": ChessQueen,
            "chess-knight": ChessKnight,
            spade: Spade,
            club: Club,
            camera: Camera,
            image: ImageIcon,
            images: Images,
            theater: Theater,
            drama: Drama,
            "venetian-mask": VenetianMask,
            "party-popper": PartyPopper,
            balloon: Balloon,
            wand: Wand,
            "wand-sparkles": WandSparkles,
            "ferris-wheel": FerrisWheel,
            "roller-coaster": RollerCoaster,
            tent: Tent,
            "tent-tree": TentTree,
            binoculars: Binoculars,
            volleyball: Volleyball,
            swords: Swords,
            sword: Sword,
            "bow-arrow": BowArrow,
            bomb: Bomb,
            ghost: Ghost,
            origami: Origami,
            "toy-brick": ToyBrick,
            blocks: Blocks,
        },
    },
    {
        label: "Nature & Pets",
        icon: "leaf",
        icons: {
            cat: Cat,
            dog: Dog,
            bird: Bird,
            rabbit: Rabbit,
            squirrel: Squirrel,
            turtle: Turtle,
            snail: Snail,
            rat: Rat,
            panda: Panda,
            worm: Worm,
            bug: Bug,
            "fish-symbol": FishSymbol,
            "paw-print": PawPrint,
            birdhouse: Birdhouse,
            "tree-deciduous": TreeDeciduous,
            "tree-pine": TreePine,
            "tree-palm": TreePalm,
            trees: Trees,
            shrub: Shrub,
            leaf: Leaf,
            sprout: Sprout,
            flower: Flower,
            "flower-2": Flower2,
            rose: Rose,
            clover: Clover,
            sun: Sun,
            sunrise: Sunrise,
            sunset: Sunset,
            moon: Moon,
            "moon-star": MoonStar,
            cloud: Cloud,
            "cloud-sun": CloudSun,
            "cloud-rain": CloudRain,
            "cloud-snow": CloudSnow,
            "cloud-lightning": CloudLightning,
            "cloud-fog": CloudFog,
            haze: Haze,
            wind: Wind,
            tornado: Tornado,
            snowflake: Snowflake,
            rainbow: Rainbow,
            umbrella: Umbrella,
            mountain: Mountain,
            "mountain-snow": MountainSnow,
            shell: Shell,
            stone: Stone,
        },
    },
    {
        label: "People",
        icon: "users",
        icons: {
            user: User,
            "user-round": UserRound,
            users: Users,
            "users-round": UsersRound,
            "user-plus": UserPlus,
            "user-check": UserCheck,
            "user-cog": UserCog,
            "user-star": UserStar,
            "circle-user-round": CircleUserRound,
            "id-card": IdCard,
            contact: Contact,
            baby: Baby,
            smile: Smile,
            laugh: Laugh,
            meh: Meh,
            frown: Frown,
            angry: Angry,
            annoyed: Annoyed,
            hand: Hand,
            "hand-heart": HandHeart,
            "hand-helping": HandHelping,
            "hand-fist": HandFist,
            "hand-metal": HandMetal,
            "thumbs-up": ThumbsUp,
            "thumbs-down": ThumbsDown,
            mars: Mars,
            venus: Venus,
            "venus-and-mars": VenusAndMars,
        },
    },
    {
        label: "Tech",
        icon: "monitor",
        icons: {
            monitor: Monitor,
            keyboard: Keyboard,
            mouse: Mouse,
            headset: Headset,
            webcam: Webcam,
            cctv: Cctv,
            tablet: Tablet,
            "tablet-smartphone": TabletSmartphone,
            "smartphone-charging": SmartphoneCharging,
            "smartphone-nfc": SmartphoneNfc,
            nfc: Nfc,
            bluetooth: Bluetooth,
            usb: Usb,
            battery: Battery,
            "battery-charging": BatteryCharging,
            cpu: Cpu,
            microchip: Microchip,
            gpu: Gpu,
            "memory-stick": MemoryStick,
            "hard-drive": HardDrive,
            "pc-case": PcCase,
            "circuit-board": CircuitBoard,
            server: Server,
            database: Database,
            router: Router,
            network: Network,
            antenna: Antenna,
            satellite: Satellite,
            "satellite-dish": SatelliteDish,
            "radio-tower": RadioTower,
            signal: Signal,
            airplay: Airplay,
            cast: Cast,
            "cloud-upload": CloudUpload,
            "cloud-download": CloudDownload,
            webhook: Webhook,
            code: Code,
            terminal: Terminal,
            braces: Braces,
            binary: Binary,
            "git-branch": GitBranch,
            "app-window": AppWindow,
            bot: Bot,
            "brain-circuit": BrainCircuit,
            fingerprint: Fingerprint,
            disc: Disc,
            globe: Globe,
            inbox: Inbox,
            send: Send,
            "message-circle": MessageCircle,
            "messages-square": MessagesSquare,
            rss: Rss,
        },
    },
    {
        label: "Places",
        icon: "building",
        icons: {
            building: Building,
            "building-2": Building2,
            factory: Factory,
            warehouse: Warehouse,
            hotel: Hotel,
            school: School,
            library: LibraryBig,
            church: Church,
            castle: Castle,
            "tower-control": TowerControl,
            dam: Dam,
            pyramid: Pyramid,
            "land-plot": LandPlot,
        },
    },
    {
        label: "Objects",
        icon: "layers",
        icons: {
            "calendar-days": CalendarDays,
            calendar: Calendar,
            "calendar-clock": CalendarClock,
            "calendar-heart": CalendarHeart,
            "calendar-range": CalendarRange,
            "calendar-sync": CalendarSync,
            clock: Clock,
            "alarm-clock": AlarmClock,
            timer: Timer,
            hourglass: Hourglass,
            history: HistoryIcon,
            watch: Watch,
            bell: Bell,
            "bell-ring": BellRing,
            star: Star,
            flag: Flag,
            "flag-triangle-right": FlagTriangleRight,
            bookmark: Bookmark,
            trophy: Trophy,
            award: Award,
            medal: Medal,
            crown: Crown,
            badge: Badge,
            "badge-check": BadgeCheck,
            lock: Lock,
            "lock-keyhole": LockKeyhole,
            unlock: Unlock,
            shield: Shield,
            "shield-check": ShieldCheck,
            paperclip: Paperclip,
            pin: Pin,
            sticker: Sticker,
            magnet: Magnet,
            "pocket-knife": PocketKnife,
            "life-buoy": LifeBuoy,
            pipette: Pipette,
            layers: Layers,
        },
    },
    {
        label: "Symbols",
        icon: "sparkles",
        icons: {
            sparkles: Sparkles,
            sparkle: Sparkle,
            bolt: Bolt,
            infinity: InfinityIcon,
            recycle: Recycle,
            "list-checks": ListChecks,
            "check-circle-2": CheckCircle2,
            check: Check,
            "check-check": CheckCheck,
            x: X,
            ban: Ban,
            "circle-help": CircleHelp,
            "circle-alert": CircleAlert,
            "alert-triangle": AlertTriangle,
            info: Info,
            hash: Hash,
            "at-sign": AtSign,
            asterisk: Asterisk,
            plus: Plus,
            minus: Minus,
            equal: Equal,
            divide: Divide,
            pi: Pi,
            sigma: Sigma,
            omega: Omega,
            atom: Atom,
            orbit: Orbit,
            eclipse: Eclipse,
            power: Power,
            command: Command,
            copyright: Copyright,
            biohazard: Biohazard,
            radiation: Radiation,
            skull: Skull,
            shapes: Shapes,
            circle: Circle,
            square: Square,
            triangle: Triangle,
            diamond: Diamond,
            pentagon: Pentagon,
            hexagon: Hexagon,
            octagon: Octagon,
            transgender: Transgender,
            "non-binary": NonBinary,
        },
    },
];

/** Ordered category grouping for the picker UI. */
export const ENTITY_ICON_CATEGORIES: ReadonlyArray<{
    label: EntityIconCategory;
    icon: string;
    names: string[];
}> = CATEGORIES.map((c) => ({ label: c.label, icon: c.icon, names: Object.keys(c.icons) }));

/**
 * Keys whose glyph is identical to another key's because Lucide renamed the
 * icon upstream and kept the old name as an alias. They stay resolvable so
 * persisted values keep rendering, but the picker lists only the canonical
 * key and `canonicalIconName()` maps them for selection state.
 */
const LEGACY_ICONS: Record<string, { icon: LucideIcon; canonical: string }> = {
    home: { icon: Home, canonical: "house" },
    train: { icon: Train, canonical: "tram" },
};

/** Legacy key → the canonical key the picker shows in its place. */
export const LEGACY_ICON_ALIASES: Readonly<Record<string, string>> = Object.fromEntries(
    Object.entries(LEGACY_ICONS).map(([key, v]) => [key, v.canonical])
);

export function canonicalIconName(name: string): string {
    return Object.prototype.hasOwnProperty.call(LEGACY_ICONS, name)
        ? LEGACY_ICONS[name]!.canonical
        : name;
}

/**
 * Flat key → component registry of every resolvable Lucide icon (legacy keys
 * included). Null prototype on purpose: the key comes straight from the
 * database, and a plain object would resolve a persisted "constructor" or
 * "__proto__" to a non-component and crash every row that renders it.
 */
export const ENTITY_ICONS: Record<string, LucideIcon> = Object.assign(
    Object.create(null) as Record<string, LucideIcon>,
    ...CATEGORIES.map((c) => c.icons),
    Object.fromEntries(Object.entries(LEGACY_ICONS).map(([key, v]) => [key, v.icon]))
);

/* One stable component per emoji so React keeps identity between renders. */
const emojiIconCache = new Map<string, EntityIconComponent>();

function emojiIcon(emoji: string): EntityIconComponent {
    let cmp = emojiIconCache.get(emoji);
    if (!cmp) {
        if (emojiIconCache.size >= 4096) {
            // Hover previews can mint one per glyph; evict the oldest rather than
            // clearing so mounted icons keep their component identity.
            const oldest = emojiIconCache.keys().next().value;
            if (oldest !== undefined) emojiIconCache.delete(oldest);
        }
        const bound: FunctionComponent<EntityIconProps> = (props) =>
            createElement(EmojiGlyph, { emoji, ...props });
        bound.displayName = `EmojiIcon(${emoji})`;
        cmp = bound;
        emojiIconCache.set(emoji, cmp);
    }
    return cmp;
}

/**
 * Resolve a persisted icon value to a component. Accepts a curated Lucide
 * key or any emoji string (with or without skin tone); anything else — an
 * unknown or removed key — renders the fallback.
 */
export function getIcon(
    name: string | null | undefined,
    fallback: EntityIconComponent = Baseline
): EntityIconComponent {
    if (!name) return fallback;
    const lucide = ENTITY_ICONS[name];
    if (lucide) return lucide;
    if (isEmojiIcon(name)) return emojiIcon(name);
    return fallback;
}
